apiVersion: v1
kind: Secret
metadata:
  name: docapinexus-secrets
  namespace: docapinexus
type: Opaque
stringData:
  JWT_SECRET: docapinexus_local_secret_change_later
  DB_USER: docapiuser
  DB_PASSWORD: DocApi@123
  DB_NAME: docapinexusdb